// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hello': string;
  'kda': string;
}
export const cssExports: CssExports;
export default cssExports;
